---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
- name: Disable SWAP since kubernetes can't work with swap enabled
  ansible.builtin.command:
    cmd: swapoff -a

- name: Remove swapfile from /etc/fstab
  ansible.posix.mount:
    name: "swap"
    fstype: swap
    state: absent

- name: Add Kubernetes gpg keys
  ansible.builtin.apt_key:
    url: "{{ kubernetes_repo_pubkey_url }}"
    state: present

- name: Add K8s repository to sources list
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /
    state: present

- name: Run the equivalent of "apt-get update"
  ansible.builtin.apt:
    update_cache: true

- name: Unhold kubeadm
  ansible.builtin.dpkg_selections:
    name: ["kubelet", "kubeadm", "kubectl"]
    selection: install
  when: upgrade_kubernetes

- name: Install Kubernetes requirements
  ansible.builtin.apt:
    name: ["kubelet={{ kubernetes_version }}", "kubeadm={{ kubernetes_version }}", "kubectl={{ kubernetes_version }}"]
    state: present

- name: Hold kubeadm
  ansible.builtin.dpkg_selections:
    name: ["kubelet", "kubeadm", "kubectl"]
    selection: hold
