containerd_version: 1.7.6
containerd_dest_file: containerd-{{ containerd_version }}-linux-amd64.tar.gz
containerd_download_url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/{{ containerd_dest_file }}

runc_version: 1.1.9
runc_download_url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64

containernet_plugins_version: 1.3.0
containernet_plugins_dest_file: cni-plugins-linux-amd64-v{{ containernet_plugins_version }}.tgz
containernet_plugins_download_url: |
  https://github.com/containernetworking/plugins/releases/download/v{{ containernet_plugins_version }}/{{ containernet_plugins_dest_file }}

upgrade_kubernetes: false
single_node_cluster: false
kubernetes_version: 1.27
kubernetes_repo_pubkey_url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key
