---
- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Validate nginx configuration
  ansible.builtin.command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
